version: "2"
services:
  gogs:
    container_name: gogs
    image: gogs/gogs:latest
    ports:
      - "10080:3000"
      - "10022:22"
    volumes:
      - /opt/docker/gogs/:/data
    environment:
      - TZ=Asia/Shanghai
    restart: always

  drone-server:
    image: drone/drone:1.2.1
    container_name: drone-server
    ports:
      - 8000:80
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data/drone/:/var/lib/drone
    environment:
      - DRONE_OPEN=true
      - DRONE_SERVER_HOST=drone-server:8000
      - DRONE_DEBUG=true
      - DRONE_GIT_ALWAYS_AUTH=false
      - DRONE_GOGS=true
      - DRONE_GOGS_SKIP_VERIFY=false
      - DRONE_GOGS_SERVER={http://192.168.xx.xx:10080}
      - DRONE_PROVIDER=gogs
      - DRONE_SERVER_PROTO=http
      - DRONE_RPC_SECRET=7b4eb5caee376cf81a2fcf7181e66175
      - DRONE_USER_CREATE=username:david,admin:true
      - DRONE_DATABASE_DATASOURCE=/var/lib/drone/drone.sqlite
      - DRONE_DATABASE_DRIVER=sqlite3
      - TZ=Asia/Shanghai
    restart: always

  drone-agent:
    image: drone/agent:1.2.1
    container_name: drone-agent
    depends_on:
      - drone-server
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DRONE_RPC_SERVER={192.168.xx.xx:9000}
      - DRONE_RPC_SECRET=7b4eb5caee376cf81a2fcf7181e66175
      - DRONE_RUNNER_CAPACITY=2
      - DRONE_DEBUG=true
      - TZ=Asia/Shanghai
    restart: always
