# aumvdown
# Autogenerated from man page /usr/share/man/man8/aumvdown.8.gz
complete -c aumvdown -s b -l lower-branch-id --description '-B | --upper-branch-id Specify the source/target branch by its id.'
complete -c aumvdown -s i -l interactive --description 'Prompt to the user for every given file.'
complete -c aumvdown -s k -l keep-upper --description 'Don\'t unlink the upper source file after copying-down.'
complete -c aumvdown -s o -l overwrite-lower --description 'Overwrite the lower target file if it exists.'
complete -c aumvdown -s r -l allow-ro-lower --description 'Do the operation even if the lower branch is marked as readonly in aufs world…'
complete -c aumvdown -s R -l allow-ro-upper --description 'Do the operation even if the upper branch is marked as readonly in aufs world…'
complete -c aumvdown -s v -l verbose --description 'Make it verbose particularly for the error cases.'
complete -c aumvdown -s h -l help --description 'Shows the command syntax. \\" . \\".'
complete -c aumvdown -s B -l upper-branch-id --description 'Specify the source/target branch by its id.'

