# debugedit
# Autogenerated from man page /usr/share/man/man8/debugedit.8.gz
complete -c debugedit -s '?' -l help --description 'Show summary of options.'
complete -c debugedit -s b -l base-dir --description 'base build directory of objects.'
complete -c debugedit -s d -l dest-dir --description 'directory to rewrite base-dir into.'
complete -c debugedit -s l -l list-file --description 'file where to put list of source and header file names.'
complete -c debugedit -s i -l build-id --description 'recompute build ID note and print ID on stdout.'

