# docker-push
# Autogenerated from man page /usr/share/man/man1/docker-push.1.gz
complete -c docker-push -l disable-content-trust --description '    Skip image signing.'
complete -c docker-push -s h -l help --description '    help for push SEE ALSO.'

