# docker-image-push
# Autogenerated from man page /usr/share/man/man1/docker-image-push.1.gz
complete -c docker-image-push -l disable-content-trust --description '    Skip image signing.'
complete -c docker-image-push -s h -l help --description '    help for push SEE ALSO.'

