# docker-engine-check
# Autogenerated from man page /usr/share/man/man1/docker-engine-check.1.gz
complete -c docker-engine-check -l containerd --description '    override default location of containerd endpoint.'
complete -c docker-engine-check -l downgrades --description '    Report downgrades (default omits older versions).'
complete -c docker-engine-check -l engine-image --description '    Specify engine image (default uses the same image as currently running).'
complete -c docker-engine-check -l format --description '    Pretty-print updates using a Go template.'
complete -c docker-engine-check -s h -l help --description '    help for check.'
complete -c docker-engine-check -l pre-releases --description '    Include pre-release versions.'
complete -c docker-engine-check -s q -l quiet --description '    Only display available versions.'
complete -c docker-engine-check -l registry-prefix --description '    Override the existing location where engine images are pulled.'
complete -c docker-engine-check -l upgrades --description '    Report available upgrades SEE ALSO.'

