# docker-engine-update
# Autogenerated from man page /usr/share/man/man1/docker-engine-update.1.gz
complete -c docker-engine-update -l containerd --description '    override default location of containerd endpoint.'
complete -c docker-engine-update -l engine-image --description '    Specify engine image (default uses the same image as currently running).'
complete -c docker-engine-update -s h -l help --description '    help for update.'
complete -c docker-engine-update -l registry-prefix --description '    Override the current location where engine images are pulled.'
complete -c docker-engine-update -l version --description '    Specify engine version SEE ALSO.'

