# docker-engine-activate
# Autogenerated from man page /usr/share/man/man1/docker-engine-activate.1.gz
complete -c docker-engine-activate -l containerd --description '    override default location of containerd endpoint.'
complete -c docker-engine-activate -l display-only --description '    only display license information and exit.'
complete -c docker-engine-activate -l engine-image --description '    Specify engine image.'
complete -c docker-engine-activate -l format --description '    Pretty-print licenses using a Go template.'
complete -c docker-engine-activate -s h -l help --description '    help for activate.'
complete -c docker-engine-activate -l license --description '    License File.'
complete -c docker-engine-activate -l quiet --description '    Only display available licenses by ID.'
complete -c docker-engine-activate -l registry-prefix --description '    Override the default location where engine images are pulled.'
complete -c docker-engine-activate -l version --description '    Specify engine version (default is to use currently running version) SEE …'

