# docker-deploy
# Autogenerated from man page /usr/share/man/man1/docker-deploy.1.gz
complete -c docker-deploy -l bundle-file --description '    Path to a Distributed Application Bundle file.'
complete -c docker-deploy -s c -l compose-file --description '    Path to a Compose file, or "-" to read from stdin.'
complete -c docker-deploy -s h -l help --description '    help for deploy.'
complete -c docker-deploy -l namespace --description '    Kubernetes namespace to use.'
complete -c docker-deploy -l prune --description '    Prune services that are no longer referenced.'
complete -c docker-deploy -l resolve-image --description '    Query the registry to resolve image digest and supported platforms ("alwa…'
complete -c docker-deploy -l with-registry-auth --description '    Send registry authentication details to Swarm agents SEE ALSO.'

