# fio2gnuplot
# Autogenerated from man page /usr/share/man/man1/fio2gnuplot.1.gz
complete -c fio2gnuplot -s h -l help --description 'The option -h displays help.'
complete -c fio2gnuplot -s p -l pattern --description 'A pattern in regexp to select fio input files.'
complete -c fio2gnuplot -s b -l bandwidth --description 'A predefined pattern for selecting *_bw. log files.'
complete -c fio2gnuplot -s i -l iops --description 'A predefined pattern for selecting *_iops. log files.'
complete -c fio2gnuplot -s g -l gnuplot --description 'Render gnuplot traces before exiting.'
complete -c fio2gnuplot -s o -l outputfile --description 'The basename for gnuplot traces (set with the pattern if defined).'
complete -c fio2gnuplot -s d -l outputdir --description 'The directory where gnuplot shall render files.'
complete -c fio2gnuplot -s t -l title --description 'The title of the gnuplot traces.'
complete -c fio2gnuplot -s G -l Global --description 'Search for \'type\' in . global files match by a pattern.'
complete -c fio2gnuplot -s m -l min_time --description 'Only consider data starting from \'time\' seconds.  Default is 0.'
complete -c fio2gnuplot -s M -l max_time --description 'Only consider data ending before \'time\' seconds.  Default is -1 aka nolimit.'
complete -c fio2gnuplot -s v -l verbose --description 'Increasing verbosity.'
complete -c fio2gnuplot -s k -l keep --description 'Keep all temporary files from gnuplot\'s output dir EXAMPLE To plot all the tr…'

