# fio_generate_plots
# Autogenerated from man page /usr/share/man/man1/fio_generate_plots.1.gz
complete -c fio_generate_plots -l bandwidth-log -s w --description 'generated in the current directory.'

