# inetutils-traceroute
# Autogenerated from man page /usr/share/man/man1/inetutils-traceroute.1.gz
complete -c inetutils-traceroute -s f -l first-hop --description 'Set initial hop distance, that is the time-to-live.'
complete -c inetutils-traceroute -s g -l gateways --description 'List of gateways for loose source routing.'
complete -c inetutils-traceroute -s I -l icmp --description 'Use ICMP ECHO as probe.'
complete -c inetutils-traceroute -s m -l max-hop --description 'Set maximal hop count (default is 64).'
complete -c inetutils-traceroute -s M -l type --description 'Use METHOD (icmp or udp) for traceroute operations, defaulting to udp.'
complete -c inetutils-traceroute -s p -l port --description 'Use destination PORT port (default is 33434).'
complete -c inetutils-traceroute -s q -l tries --description 'Send NUM probe packets per hop (default is 3).'
complete -c inetutils-traceroute -l resolve-hostnames --description 'Resolve hostnames.'
complete -c inetutils-traceroute -s t -l tos --description 'Set type of service (TOS) to NUM.'
complete -c inetutils-traceroute -s w -l wait --description 'Wait NUM seconds for response (default is 3).'
complete -c inetutils-traceroute -s '?' -l help --description 'Give this help list.'
complete -c inetutils-traceroute -l usage --description 'Give a short usage message.'
complete -c inetutils-traceroute -s V -l version --description 'Print program version.'

