# master
# Autogenerated from man page /usr/share/man/man8/master.8postfix.gz
complete -c master -s c --description 'Read the main. cf and master.'
complete -c master -s D --description 'After initialization, run a debugger on the master process.'
complete -c master -s d --description 'Do not redirect stdin, stdout or stderr to /dev/null, and do not discard the …'
complete -c master -s e --description 'Terminate the master process after exit_time seconds.'
complete -c master -s t --description 'Test mode.  Return a zero exit status when the master.'
complete -c master -s v --description 'Enable verbose logging for debugging purposes.'
complete -c master -s w --description 'Wait in a dummy foreground process, while the real master daemon initializes …'

