# qmqp-source
# Autogenerated from man page /usr/share/man/man1/qmqp-source.1.gz
complete -c qmqp-source -s 4 --description 'Connect to the server with IPv4.'
complete -c qmqp-source -s 6 --description 'Connect to the server with IPv6.'
complete -c qmqp-source -s c --description 'Display a running counter that is incremented each time a delivery completes.'
complete -c qmqp-source -s C --description 'When a host sends RESET instead of SYN|ACK, try count times before giving up.'
complete -c qmqp-source -s f --description 'Use the specified sender address (default: <foo@myhostname>).'
complete -c qmqp-source -s l --description 'Send length bytes as message payload.'
complete -c qmqp-source -s m --description 'Send the specified number of messages (default: 1).'
complete -c qmqp-source -s M --description 'Use the specified hostname or [address] in the default sender and recipient a…'
complete -c qmqp-source -s r --description 'Send the specified number of recipients per transaction (default: 1).'
complete -c qmqp-source -s s --description 'Run the specified number of QMQP sessions in parallel (default: 1).'
complete -c qmqp-source -s t --description 'Use the specified recipient address (default: <foo@myhostname>).'
complete -c qmqp-source -s R --description 'Wait for a random period of time 0 <= n <= interval between messages.'
complete -c qmqp-source -s v --description 'Make the program more verbose, for debugging purposes.'
complete -c qmqp-source -s w --description 'Wait a fixed time between messages.'

