# qshape
# Autogenerated from man page /usr/share/man/man1/qshape.1.gz
complete -c qshape -s s --description 'Display the sender domain distribution instead of the recipient domain distri…'
complete -c qshape -s p --description 'Generate aggregate statistics for parent domains.'
complete -c qshape -s m --description 'When used with the -p option, sets the minimum subdomain count needed to show…'
complete -c qshape -s b --description 'The age distribution is broken up into a sequence of geometrically increasing…'
complete -c qshape -s t --description 'The age limit in minutes for the first time bucket.'
complete -c qshape -s l --description 'Instead of using a geometric age sequence, use a linear age sequence, in othe…'
complete -c qshape -s w --description 'The output is right justified, with the counts for the last bucket shown on t…'
complete -c qshape -s N --description 'When the output device is a terminal, intermediate results are shown each "ba…'
complete -c qshape -s n --description 'When reporting intermediate or final results to a termainal, report only the …'
complete -c qshape -s c --description 'The main.'

