# stap-merge
# Autogenerated from man page /usr/share/man/man1/stap-merge.1.gz
complete -c stap-merge -s v --description 'Verbose mode, displays three extra fields per set of collected data.'
complete -c stap-merge -s o --description '.'

